#!/usr/bin/env python3
"""Regenerate screenshots/index.html: a thumbnail gallery, newest first.

Picks up .png and .gif -- the store preview is an animation.

screenshots/ is served over the LAN by `python3 -m http.server` from inside it,
which has no way to run anything, so the listing has to be a static file. Run
this after adding shots.
"""
import html
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))
SHOTS = os.path.join(os.path.dirname(HERE), "screenshots")

PAGE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Shaot watchface — screenshots</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body {{ background: #1a1a1c; color: #ddd; font-family: system-ui, sans-serif;
         margin: 0; padding: 2em; }}
  h1 {{ font-size: 1.3em; font-weight: 600; margin: 0 0 .3em; }}
  p.note {{ color: #999; max-width: 52em; line-height: 1.55; margin: .3em 0 0; }}
  a {{ color: #6cf; }}
  .grid {{ display: flex; flex-wrap: wrap; gap: 1.6em; margin-top: 2em;
          align-items: flex-start; }}
  figure {{ margin: 0; max-width: 220px; }}
  img {{ image-rendering: pixelated; border: 1px solid #444; border-radius: 8px;
        display: block; max-width: 100%; background: #000; }}
  figcaption {{ margin-top: .5em; font-size: .82em; color: #999;
               word-break: break-all; }}
  figcaption .when {{ color: #666; }}
</style>
</head>
<body>
<h1>Shaot watchface — screenshots</h1>
<p class="note">Newest first. Emulator captures at 200×228 unless they are
comparison strips, which are wider. Also here:
<a href="layout-choice.html">the layout-choice page</a> from the design stage.</p>
<div class="grid">
{tiles}
</div>
<p class="note" style="margin-top:2em">Generated by
<code>tools/screenshot-index.py</code> at {stamp}.</p>
</body>
</html>
"""

TILE = """  <figure>
    <a href="{name}"><img src="{name}" alt="{name}" loading="lazy"></a>
    <figcaption>{name}<br><span class="when">{when}</span></figcaption>
  </figure>"""


def main():
    shots = [f for f in os.listdir(SHOTS)
             if f.lower().endswith((".png", ".gif"))]
    shots.sort(key=lambda f: os.path.getmtime(os.path.join(SHOTS, f)), reverse=True)
    tiles = "\n".join(
        TILE.format(
            name=html.escape(f),
            when=time.strftime("%Y-%m-%d %H:%M",
                               time.localtime(os.path.getmtime(os.path.join(SHOTS, f)))),
        )
        for f in shots
    )
    out = os.path.join(SHOTS, "index.html")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(PAGE.format(tiles=tiles, stamp=time.strftime("%Y-%m-%d %H:%M")))
    print("%s: %d screenshots" % (out, len(shots)))


if __name__ == "__main__":
    main()
